# Site settings
title: "BD#15"
description: "BD#15"
baseurl: "/15" # the subpath of your site, e.g. /blog
url: "https://obdhub.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "BD#15"
user_description: "Many people will walk in and out of your life. But only true friends will leave footprints in your heart."
user_title: "บดินทรเดชา (สิงห์ สิงหเสนี) รุ่น ๑๕"
email: odd.daboss@gmail.com
twitter_username: odd_daboss
github_username:  obdhub/15
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
